# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [6]:
import numpy as np
import random

#### 2. Print your NumPy version.

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [20]:
a1 = np.random.rand(2,3,5)
a1

array([[[0.76412013, 0.12849332, 0.2901806 , 0.36521469, 0.17072953],
        [0.78168399, 0.36477726, 0.41864428, 0.81287788, 0.79763183],
        [0.26445359, 0.08809761, 0.94971027, 0.27191194, 0.82756649]],

       [[0.18820196, 0.63246562, 0.05854403, 0.84405374, 0.60691774],
        [0.70282871, 0.42308527, 0.82656922, 0.81332429, 0.80061023],
        [0.98118827, 0.87633199, 0.33555348, 0.64167952, 0.3917207 ]]])

In [7]:
# Method 2

a = [[[random.random() for i in range(5)] for j in range(3)] for n in range(2)]
a

[[[0.990281637135951,
   0.8754849939692126,
   0.6343048945777828,
   0.3032838818038458,
   0.7649005751273623],
  [0.40735435777017814,
   0.11899506698268647,
   0.5949129770937521,
   0.09852579691561336,
   0.6941988006427638],
  [0.5713076649839172,
   0.7781850678248317,
   0.9934346442225047,
   0.22414461694482857,
   0.1876132938179914]],
 [[0.9288095608013912,
   0.8325339121643359,
   0.2874893118994365,
   0.31692972243325146,
   0.5022929863348439],
  [0.8733675016088936,
   0.18855765008442815,
   0.5386494382880777,
   0.2676122469709067,
   0.4169391507788003],
  [0.9408314308543658,
   0.6618753089259694,
   0.2241692735858477,
   0.5948350217380249,
   0.021514601416176893]]]

In [ ]:
# Method 3

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [9]:
# your code here

b = np.ones((5,2,3))
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [21]:
# your code here
a1.size

30

In [18]:
b.size

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [22]:
# your answer here

ad = np.add(a1,b)
ad

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [23]:
len(a1)

2

In [24]:
len(b)

5

In [ ]:
# We can't add a1 & b beacuse they don't have the same length although they have the same size.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [28]:
# your code here

c = np.transpose(b, (1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [29]:
# your code/answer here

d = np.add(a1,c)
d

array([[[1.76412013, 1.12849332, 1.2901806 , 1.36521469, 1.17072953],
        [1.78168399, 1.36477726, 1.41864428, 1.81287788, 1.79763183],
        [1.26445359, 1.08809761, 1.94971027, 1.27191194, 1.82756649]],

       [[1.18820196, 1.63246562, 1.05854403, 1.84405374, 1.60691774],
        [1.70282871, 1.42308527, 1.82656922, 1.81332429, 1.80061023],
        [1.98118827, 1.87633199, 1.33555348, 1.64167952, 1.3917207 ]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [30]:
# your code/answer here
a1

array([[[0.76412013, 0.12849332, 0.2901806 , 0.36521469, 0.17072953],
        [0.78168399, 0.36477726, 0.41864428, 0.81287788, 0.79763183],
        [0.26445359, 0.08809761, 0.94971027, 0.27191194, 0.82756649]],

       [[0.18820196, 0.63246562, 0.05854403, 0.84405374, 0.60691774],
        [0.70282871, 0.42308527, 0.82656922, 0.81332429, 0.80061023],
        [0.98118827, 0.87633199, 0.33555348, 0.64167952, 0.3917207 ]]])

In [ ]:
# a1 has the same values and size as d.

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [31]:
# your code here

e = np.dot(a1,c)
e

ValueError: shapes (2,3,5) and (2,3,5) not aligned: 5 (dim 2) != 3 (dim 1)

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
# can not multiple a1 & c

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [32]:
# your code here

d_max = np.amax(d)
d_min = np.amin(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)

1.9811882695126868 1.0585440303379747 1.5473056071193056


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [33]:
# your code here

f = np.empty_like(d)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [38]:
# your code here

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for n in range(d.shape[2]):
            if d_min < d[i,j,n] < d_mean:
                f[i,j,n] = 25
            elif d_mean < d[i,j,n] < d_max:
                f[i,j,n] = 75
            elif d[i,j,n] == d_mean:
                f[i,j,n] = 50
            elif d[i,j,n] == d_min:
                f[i,j,n] = 0
            elif d[i,j,n] == d_max:
                f[i,j,n] = 100
        
f

array([[[ 75.,  25.,  25.,  25.,  25.],
        [ 75.,  25.,  25.,  75.,  75.],
        [ 25.,  25.,  75.,  25.,  75.]],

       [[ 25.,  75.,   0.,  75.,  75.],
        [ 75.,  25.,  75.,  75.,  75.],
        [100.,  75.,  25.,  75.,  25.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [40]:
# your code here

f = np.empty_like(d, dtype=str)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for n in range(d.shape[2]):
            if d_min < d[i,j,n] < d_mean:
                f[i,j,n] = "B"
            elif d_mean < d[i,j,n] < d_max:
                f[i,j,n] = "D"
            elif d[i,j,n] == d_mean:
                f[i,j,n] = "C"
            elif d[i,j,n] == d_min:
                f[i,j,n] = "A"
            elif d[i,j,n] == d_max:
                f[i,j,n] = "E"
        
f

array([[['D', 'B', 'B', 'B', 'B'],
        ['D', 'B', 'B', 'D', 'D'],
        ['B', 'B', 'D', 'B', 'D']],

       [['B', 'D', 'A', 'D', 'D'],
        ['D', 'B', 'D', 'D', 'D'],
        ['E', 'D', 'B', 'D', 'B']]], dtype='<U1')